name: nice_json
description: A nice way to encode nice maps into nice-looking, human-readable json.
version: 1.1.2
repository: https://github.com/alexobviously/nice_json
issue_tracker: https://github.com/alexobviously/nice_json/issues

environment:
  sdk: ^3.0.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
